name: Build APK

on:
  push:
    branches:
      - main  # jab main branch pe koi bhi commit hoga, yeh action chalega
  pull_request:
    branches:
      - main  # jab pull request banega to bhi yeh action chalega

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu par workflow run hoga

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Repository ko checkout karega

    - name: Set up Python
      uses: actions/setup-python@v2  # Python environment setup karega
      with:
        python-version: '3.9'  # Python version specify karein

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Agar aapke project me koi dependencies hain to

    - name: Install Buildozer and dependencies
      run: |
        pip install buildozer
        sudo apt update
        sudo apt install -y python3-dev build-essential ccache git
        sudo apt install -y libncurses5 libstdc++6 libssl-dev libffi-dev
        sudo apt install -y libsqlite3-dev

    - name: Build APK
      run: |
        buildozer android debug  # APK ko build karega

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: bin/*.apk  # Jo APK build hogi usko artifact ke roop mein upload karega

    - name: Commit APK (optional)
      run: |
        git add bin/*.apk
        git commit -m "Add APK build"
        git push
